name: Build and Push to GHCR

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    env:
      IMAGE_NAME: ghcr.io/bonejob/capitol-theatre

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Tag Name
        id: get_tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u Bonejob --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ steps.get_tag.outputs.tag }} .

      - name: Push Docker Images
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.get_tag.outputs.tag }}
